[terminal]
vt = 1

[default_session]
command = "tuigreet --time --remember --user-menu --theme 'text=brightwhite;prompt=cyan;border=magenta;container=black;input=brightcyan;button=yellow;action=green;time=brightmagenta' --cmd Hyprland"
user = "greeter"
